spring.application.name=clinical-service
server.port=8079

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/clinical_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

user.service.base-url=http://localhost:8069/api/users


